name: Node.js CI

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: arc-runner-set

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build:
    needs: test
    runs-on: arc-runner-set

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            dist
            package.json
            package-lock.json
            Dockerfile

  docker:
    needs: build
    runs-on: arc-runner-set

    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: remote
          endpoint: tcp://buildkit.buildkit.svc.cluster.local:1234

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ts-backend-demo:latest
            ghcr.io/${{ github.repository_owner }}/ts-backend-demo:${{ github.sha }}

  update-gitops:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Update GitOps repo
        env:
          GITOPS_TOKEN: ${{ secrets.HOMELAB_APPS_PAT }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          git clone https://x-access-token:${GITOPS_TOKEN}@github.com/rubenspensky-homelab/homelab-apps.git
          cd homelab-apps
          sed -i "s|image: .*|image: ghcr.io/rubenspensky-homelab/ts-backend-demo:${IMAGE_TAG}|" \
          infrastructure/ts-backend-demo/deployment.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add infrastructure/ts-backend-demo/deployment.yaml
          git commit -m "chore: update ts-backend-demo image to ${IMAGE_TAG}"
          git push
